Repository tweag/asterius, pull requests merged in 2020-01, with the labels that each got.

#415 Add stack-ide.sh
  utils/readme.md
  utils/stack-ide.sh
Labels: P2, type: feature request

#416 Recover support for the TeeLocal opcode
  asterius/src/Asterius/Backends/Binaryen.hs
  asterius/src/Asterius/Backends/WasmToolkit.hs
  asterius/src/Asterius/Types.hs
Labels: P1, type: feature request

#417 Add cmath cbits
  asterius/src/Asterius/Builtins.hs
  asterius/src/Asterius/Builtins/CMath.hs
Labels: P1, type: feature request

#418 Implement parts of StgPrimFloat
  asterius/src/Asterius/Builtins.hs
  asterius/src/Asterius/Builtins/StgPrimFloat.hs
Labels: P1, type: feature request

#419 Implement __decodeDouble_2Int
  asterius/rts/rts.float.mjs
  asterius/src/Asterius/Builtins.hs
Labels: P1, type: bug

#386 Use stock `integer-simple` and recover `JSVal` garbage collection
  asterius/rts/rts.gc.mjs
  asterius/rts/rts.integer.mjs
  asterius/rts/rts.mjs
  asterius/rts/rts.stableptr.mjs
  asterius/src/Asterius/Ld.hs
  ghc-toolkit/boot-libs/integer-simple/GHC/Integer.hs
  ghc-toolkit/boot-libs/integer-simple/GHC/Integer/Logarithms/Internals.hs
  ghc-toolkit/boot-libs/integer-simple/GHC/Integer/Type.hs
Labels: P1, type: bug

#420 Run limit-segments pass after binaryen optimization
  asterius/src/Asterius/Backends/Binaryen.hs
  asterius/src/Asterius/JSRun/NonMain.hs
  asterius/src/Asterius/Main.hs
Labels: P1, type: bug

#421 No-op threadPaused
  asterius/rts/rts.mjs
  asterius/rts/rts.threadpaused.mjs
  asterius/src/Asterius/Builtins.hs
Labels: P1, type: bug

#423 (WIP) More comments in the RTS source code
  asterius/rts/rts.gc.mjs
  asterius/rts/rts.heapalloc.mjs
  asterius/rts/rts.memory.mjs
Labels: type: documentation

#427 Add a direnv config file for convenience
  .envrc
Labels: P3, type: feature request

#429 Test more cabal packages on CI
  .circleci/config.yml
Labels: P1, type: bug

#431 Make sure all unary/binary ops are present in the EDSL
  asterius/src/Asterius/Builtins.hs
  asterius/src/Asterius/Builtins/CMath.hs
  asterius/src/Asterius/Builtins/StgPrimFloat.hs
  asterius/src/Asterius/CodeGen.hs
  asterius/src/Asterius/EDSL.hs
  asterius/src/Asterius/EDSL/BinaryOp.hs
  asterius/src/Asterius/EDSL/UnaryOp.hs
  asterius/src/Asterius/Passes/GlobalRegs.hs
  asterius/src/Asterius/Passes/MergeSymbolOffset.hs
  asterius/src/Asterius/Passes/SafeCCall.hs
Labels: P2, type: feature request

#432 Reuse FNV-1a logic of `hashable` for MD5 stub implementation for `base`
  asterius/rts/rts.fnv.mjs
  asterius/rts/rts.md5.mjs
  asterius/rts/rts.memory.mjs
  asterius/rts/rts.mjs
  asterius/src/Asterius/Builtins.hs
  asterius/src/Asterius/Builtins/Hashable.hs
  asterius/src/Asterius/Builtins/MD5.hs
Labels: P2, type: feature request

#430 Bugfix - Use forwarding pointers during GC
  asterius/rts/rts.gc.mjs
Labels: P1

#436 Tune rtsopts for asterius executables
  .circleci/config.yml
  asterius/package.yaml
Labels: P2, type: feature request

#437 Infra update for ghc-8.6
  ghc-toolkit/boot-libs/cabal.config
  lts.sh
  stack.yaml
Labels: P2, type: feature request

#438 Fix Cabal 3 support of ghc-toolkit
  ghc-toolkit/Setup.hs
  ghc-toolkit/src/Language/Haskell/GHC/Toolkit/GenPaths.hs
Labels: P1, type: bug

#440 Update rts.unicode.mjs
  asterius/rts/rts.unicode.mjs
Labels: P2, type: bug
